# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import reddit_service_pb2 as reddit__service__pb2


class RedditStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePost = channel.unary_unary(
                '/Reddit/CreatePost',
                request_serializer=reddit__service__pb2.CreatePostRequest.SerializeToString,
                response_deserializer=reddit__service__pb2.Post.FromString,
                )
        self.VotePost = channel.unary_unary(
                '/Reddit/VotePost',
                request_serializer=reddit__service__pb2.VotePostRequest.SerializeToString,
                response_deserializer=reddit__service__pb2.Post.FromString,
                )
        self.GetPost = channel.unary_unary(
                '/Reddit/GetPost',
                request_serializer=reddit__service__pb2.GetPostRequest.SerializeToString,
                response_deserializer=reddit__service__pb2.Post.FromString,
                )
        self.CreateComment = channel.unary_unary(
                '/Reddit/CreateComment',
                request_serializer=reddit__service__pb2.CreateCommentRequest.SerializeToString,
                response_deserializer=reddit__service__pb2.Comment.FromString,
                )
        self.VoteComment = channel.unary_unary(
                '/Reddit/VoteComment',
                request_serializer=reddit__service__pb2.VoteCommentRequest.SerializeToString,
                response_deserializer=reddit__service__pb2.Comment.FromString,
                )
        self.GetTopComments = channel.unary_unary(
                '/Reddit/GetTopComments',
                request_serializer=reddit__service__pb2.GetTopCommentsRequest.SerializeToString,
                response_deserializer=reddit__service__pb2.TopCommentsResponse.FromString,
                )
        self.ExpandCommentBranch = channel.unary_unary(
                '/Reddit/ExpandCommentBranch',
                request_serializer=reddit__service__pb2.ExpandCommentBranchRequest.SerializeToString,
                response_deserializer=reddit__service__pb2.ExpandCommentBranchResponse.FromString,
                )


class RedditServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VotePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VoteComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopComments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExpandCommentBranch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RedditServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePost': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePost,
                    request_deserializer=reddit__service__pb2.CreatePostRequest.FromString,
                    response_serializer=reddit__service__pb2.Post.SerializeToString,
            ),
            'VotePost': grpc.unary_unary_rpc_method_handler(
                    servicer.VotePost,
                    request_deserializer=reddit__service__pb2.VotePostRequest.FromString,
                    response_serializer=reddit__service__pb2.Post.SerializeToString,
            ),
            'GetPost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPost,
                    request_deserializer=reddit__service__pb2.GetPostRequest.FromString,
                    response_serializer=reddit__service__pb2.Post.SerializeToString,
            ),
            'CreateComment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateComment,
                    request_deserializer=reddit__service__pb2.CreateCommentRequest.FromString,
                    response_serializer=reddit__service__pb2.Comment.SerializeToString,
            ),
            'VoteComment': grpc.unary_unary_rpc_method_handler(
                    servicer.VoteComment,
                    request_deserializer=reddit__service__pb2.VoteCommentRequest.FromString,
                    response_serializer=reddit__service__pb2.Comment.SerializeToString,
            ),
            'GetTopComments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopComments,
                    request_deserializer=reddit__service__pb2.GetTopCommentsRequest.FromString,
                    response_serializer=reddit__service__pb2.TopCommentsResponse.SerializeToString,
            ),
            'ExpandCommentBranch': grpc.unary_unary_rpc_method_handler(
                    servicer.ExpandCommentBranch,
                    request_deserializer=reddit__service__pb2.ExpandCommentBranchRequest.FromString,
                    response_serializer=reddit__service__pb2.ExpandCommentBranchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Reddit', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Reddit(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Reddit/CreatePost',
            reddit__service__pb2.CreatePostRequest.SerializeToString,
            reddit__service__pb2.Post.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VotePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Reddit/VotePost',
            reddit__service__pb2.VotePostRequest.SerializeToString,
            reddit__service__pb2.Post.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Reddit/GetPost',
            reddit__service__pb2.GetPostRequest.SerializeToString,
            reddit__service__pb2.Post.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Reddit/CreateComment',
            reddit__service__pb2.CreateCommentRequest.SerializeToString,
            reddit__service__pb2.Comment.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VoteComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Reddit/VoteComment',
            reddit__service__pb2.VoteCommentRequest.SerializeToString,
            reddit__service__pb2.Comment.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTopComments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Reddit/GetTopComments',
            reddit__service__pb2.GetTopCommentsRequest.SerializeToString,
            reddit__service__pb2.TopCommentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExpandCommentBranch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Reddit/ExpandCommentBranch',
            reddit__service__pb2.ExpandCommentBranchRequest.SerializeToString,
            reddit__service__pb2.ExpandCommentBranchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
